[package]
name = "vge"
version = "0.1.0"
edition = "2024"

[dependencies]
smol = "2.0.2"
thiserror = "2.0.7"
tracing = "0.1.41"
wgpu = "23.0.1"
winit = "0.30.5"

[dev-dependencies]
smol = "2.0.2"
tracing-subscriber = "0.3.19"
