[package]
name = "vge_app"
version = "0.1.0"
edition = "2024"

[dependencies]
vge_core = { path = "../vge_core" }
vge_render = { path = "../vge_render" }
vge_window = { path = "../vge_window" }

thiserror = "2.0.7"
